##task file in the 'create-alb' role to create the alb
---
- name: to create alb
  elb_application_lb:
    name: "{{ alb_name }}"
    subnets:
      - "{{ subnet_1 }}"
      - "{{ subnet_2 }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
      - Protocol: HTTPS
        Port: 443
        DefaultActions:
          - Type: forward  
    state: present
  register: alb
