##task file in 'build-image' role to push the docker image to repository
##assumption: The repository is a Git repository
---
- name: Log in to Docker Hub repo
  docker_login:
    username: "{{ docker_user }}"
    password: "{{ docker_pass }}"
    
 - name: Build Docker image and push to Docker Hub repo
   docker_image:
     build:
       path: ./docker
     name: "{{ docker_repo }}/{{ app_name }}"
     push: yes
     source: build
     force_source: yes
