##Playbook 1 - To create application ALB
##Playbook name: alb.yml
##Assumption 1: hosts are mentioned in default inventory file
##Assumption 2: All the required variable values are given as general variable
##Assumption 3: VPCs,Subnets have been already created.
---
- name: Playbook to create ALB
  hosts: localhost ##Linux machine in which Ansible is installed
  gather_facts: false
  connection: local
  roles:
    - role: '../roles/create-alb' ##roles can be created with ansible galaxy commands
